language: go
go:
  - 1.7

addons:
  apt:
    packages:
      - nodejs

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - npm install

script:
  - go test -v ./...

after_success:
  - npm run build
