language: go
go:
  - 1.7

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - go test -v ./dashboard/

after_success:
  - go build -v
  - npm run build
